### ISSUE TITLE
`null` array access + method invocation

### ISSUE THREAD

**Issue by problame** [comprakt/comprakt#108]
**Semcheck** could **warn** about this. A commit with the current suboptimal behavior will reference this issue in a few minutes.

**IR codegen** will need a decision on this topic.

**Comment by problame** [comment]
Proposal: our compiler should generate code that checks for UB and crashes the program when it would happen, producing a nice stack trace.
The runtime support for this has been implemented in
https://github.com/comprakt/comprakt/pull/136/commits/cde2c6ad1fbb6822d1d48f17f2d7c6f030b38284 .

See https://github.com/comprakt/comprakt/pull/136/commits/7dcb98c388cfe1f41b78b47c6e894e32a855943c for an example on how to use those functions.

**Comment by joshuabach** [comment]
See #220

**Comment by problame** [comment]
Isn't that a runtime-crash?

Technically, we could emit warnings if we scanned the FIRM graph for unconditionally executed `mjrt_...panics` calls. I guess that won't cover a lot of cases, though.

If that is too complicated / dev time consuming (it likely is), close this issue and get #220 done, it's more than good enough to panic at runtime!
