### ISSUE TITLE
Lowering of functions with arguments

### ISSUE THREAD

**Issue by joshuabach** [comprakt/comprakt#194]
When lowering a function with args (in current `josh+problame/lowering`) we get

```
thread 'main' panicked at 'predecessor must produce value', compiler-lib/src/lowering/gen_instr.rs:262:21
```

This is because the argument node (`Proj T T_args`) is not marked as computed (because it is, in fact, not computed). I guess we need to think about calling conventions for this.

**Comment by problame** [comment]
do you have a reproducer?

**Comment by problame** [comment]
a fix for anything related to `not computed` landed in #234 https://github.com/comprakt/comprakt/pull/234/commits/9ef0a1d3285ee94697a351845b9c461f1f7a67f4

**Comment by problame** [comment]
bump

**Comment by joshuabach** [comment]
I opend this issue before we even thought about this (it was obviously not implemented then); i don't have a special reproducer. Since all mjtests/integration tests pass in current master (and they include arguments) I assume this is resolved
