### ISSUE TITLE
Double phi nodes within one block

### ISSUE THREAD

**Issue by joshuabach** [comprakt/comprakt#196]
Our LIR currently can't handle programs like this:
```java
    public int foo() {
        int x = 0;

        int i = 0;
        while (i < 10) {
            x = i;
            i = i + 1;
        }

        return x;
    }
```
This is because it results in a structure like this:
![2019-01-07_12-31_firm_lostcopy](https://user-images.githubusercontent.com/12047122/50766161-7e8c2500-1278-11e9-9e03-78ad7f4f8167.png)

The problem here is that, unlike in any other cases, we need a seperate slot for the phi node and a multislot for the union of its predecessors.

I'm really at the end with my latin here. *#givingup*

**Comment by problame** [comment]
fixed in 961af6b83a338564922546d752fcb380774d6ed2
