### ISSUE TITLE
Remove critical edges

### ISSUE THREAD

**Issue by joshuabach** [comprakt/comprakt#199]
We need to handle lost copies (generated by e.g. short-circuiting boolean operators). We have some options here:
 - Port libfirm's `remove_critical_cf_edges` from C
 - Use `must_copy_in_source(...) && must_copy_in_target(...)` check and create LIR-blocks without a corresponding firm-block

**Comment by problame** [comment]
see #200

**Comment by reiner-dolp** [comment]
This is already merged.
