### ISSUE TITLE
Compile Libfirm in Release Mode

### ISSUE THREAD

**Issue by reiner-dolp** [comprakt/comprakt#238]
I am currently looking at flame graphs, ~a few percent of the runtime are spent on running verification routines that should be disabled when `DEBUG_libfirm` is not set. However, I don't see where the flag is set.~ The only offending function is `ir_verify_arr` which is feature gated by `NDEBUG`.

`NDEBUG` might only be set because I am building a release binary with debug symbols... not sure. We have to dig into the rust compiler source for this.

Priority Middle: there are routines spending way more time on the CPU, that should be worked on first.

**Comment by flip1995** [comment]
implemented in 9ecfa8ec599c57a22777421b338be3195a23d8e6
