### ISSUE TITLE
Update Rust

### ISSUE THREAD

**Issue by joshuabach** [comprakt/comprakt#24]
We should bump the nightly to the latest release, because NLL is here!!

http://smallcultfollowing.com/babysteps/blog/2018/10/31/mir-based-borrowck-is-almost-here/

**Comment by joshuabach** [comment]
We *really* should do this. Lifetime errors are no much better, for instance "anonymous lifetimes" are now given a name in the compiler output :heart: 
```
error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> src/parser.rs:164:13
    |
159 |       fn consume(&mut self, want: ExpectedToken) -> SyntaxResult<'_, Token<'_>> {
    |                  - let's call the lifetime of this reference `'1`
160 |           let got = self.peek()?;
    |                     ---- first mutable borrow occurs here
...
164 |               self.next()
    |               ^^^^ second mutable borrow occurs here
165 |           } else {
166 | /             Err(SyntaxError::UnexpectedToken {
167 | |                 got: got.clone(),
168 | |                 expected: want,
169 | |             })
    | |______________- returning this value requires that `*self` is borrowed for `'1`
```

**Comment by flip1995** [comment]
We need to wait until the mac-os nightly is available again. ETA tomorrow. Or when was nll enabled by default in edition 2018?

**Comment by joshuabach** [comment]
There also doesn't seem to be a `rustfmt` for the latest nightly

**Comment by flip1995** [comment]
Clippy is missing. `rustfmt` should be in the latest nightly: https://mexus.github.io/rustup-components-history/

**Comment by flip1995** [comment]
Tomorrow rustfmt, clippy and rls will be included in the nightly again (if no breaking PR gets merged until then). After that we can bump the nightly version.
