### ISSUE TITLE
cleanup main

### ISSUE THREAD

**Issue by reiner-dolp** [comprakt/comprakt#55]
- Contains dead code
- duplicated code, e.g. `unforgiving_lexer`
- contains tests for the lexer...

**Comment by reiner-dolp** [comment]
most of this was done in pull-request #83.

**Comment by reiner-dolp** [comment]
needs only deduplication now

**Comment by problame** [comment]
Let's consider this done as of 58f35a7eacd92a207e5504d53267a39d038b594a
