### ISSUE TITLE
Take advantage of strum dependency in lexer

### ISSUE THREAD

**Issue by reiner-dolp** [comprakt/comprakt#56]
The AST introduces the "strum" crate which can generate a mapping from enum variants to strings automatically. Use it in the parser to generate mappings for keywords.

**Comment by problame** [comment]
I'm happy with our current macro. I don't think strum buys us anything here, since all the mappings will be spread over `#[...]` variant annotations.

**Comment by reiner-dolp** [comment]
I am not talking about any macro, (we are not using one in the lexer anyways?) but the lexer contains a huge list of String=>Enum and Enum->String conversions written by hand where the enum variant name is equivalent to the string contents. Strum can generate these automatically.

For example:
```rust
impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        use self::Keyword::*;
        write!(
            f,
            "{}",
            match self {
                Abstract => "abstract",
                Assert => "assert",
                Boolean => "boolean",
                Break => "break",
                Byte => "byte",
                Case => "case",
                Catch => "catch",
                Char => "char",
                Class => "class",
                Const => "const",
                Continue => "continue",
                Default => "default",

```

**Comment by problame** [comment]
@reiner-dolp are you ok with closing this?
